#git  -C   ../mirror/apache-site-git/hadoop-site/                         checkout     -f
#git  -C   ../mirror/apache-site-git/hbase-site/                          checkout     -f
#git  -C   ../mirror/apache-site-git/spark-website/                       checkout     -f  
#git  -C   ../mirror/apache-site-git/storm-site/                          checkout     -f
                                              
git  -C   ../mirror/apache-site-git/accumulo-website/                    checkout     -f  
git  -C   ../mirror/apache-site-git/activemq-website/                    checkout     -f  
git  -C   ../mirror/apache-site-git/airavata-site/                       checkout     -f  
git  -C   ../mirror/apache-site-git/airflow-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/allura-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/apachecon-site/                      checkout     -f  
git  -C   ../mirror/apache-site-git/apache-website-template/             checkout     -f  
git  -C   ../mirror/apache-site-git/apex-site/                           checkout     -f  
git  -C   ../mirror/apache-site-git/archiva-redback-components-site/     checkout     -f  
git  -C   ../mirror/apache-site-git/archiva-redback-site/                checkout     -f  
git  -C   ../mirror/apache-site-git/archiva-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/arrow-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/asterixdb-site/                      checkout     -f  
git  -C   ../mirror/apache-site-git/atlas-website/                       checkout     -f  
git  -C   ../mirror/apache-site-git/attic-polygene-website/              checkout     -f  
git  -C   ../mirror/apache-site-git/attic-wink-website/                  checkout     -f  
git  -C   ../mirror/apache-site-git/aurora-website/                      checkout     -f  
git  -C   ../mirror/apache-site-git/bahir-website/                       checkout     -f  
git  -C   ../mirror/apache-site-git/beam-site/                           checkout     -f  
git  -C   ../mirror/apache-site-git/calcite-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/camel-website/                       checkout     -f  
git  -C   ../mirror/apache-site-git/carbondata-site/                     checkout     -f  
git  -C   ../mirror/apache-site-git/cayenne-website/                     checkout     -f  
git  -C   ../mirror/apache-site-git/celix-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/comdev-wwwsite/                      checkout     -f  
git  -C   ../mirror/apache-site-git/creadur-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/db-jdo-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/drill-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/fineract-site/                       checkout     -f  
git  -C   ../mirror/apache-site-git/flex-site/                           checkout     -f  
git  -C   ../mirror/apache-site-git/flex-site-ng/                        checkout     -f  
git  -C   ../mirror/apache-site-git/fluo-website/                        checkout     -f  
git  -C   ../mirror/apache-site-git/freemarker-site/                     checkout     -f  
git  -C   ../mirror/apache-site-git/geode-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/geronimo-website/                    checkout     -f  
git  -C   ../mirror/apache-site-git/griffin-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/groovy-dev-site/                     checkout     -f  
git  -C   ../mirror/apache-site-git/groovy-user-site/                    checkout     -f  
git  -C   ../mirror/apache-site-git/groovy-website/                      checkout     -f  
git  -C   ../mirror/apache-site-git/guacamole-website/                   checkout     -f  
git  -C   ../mirror/apache-site-git/hadoop-ozonesite/                    checkout     -f  
                                                                     
git  -C   ../mirror/apache-site-git/hawq-site/                           checkout     -f  
                                                                        
git  -C   ../mirror/apache-site-git/httpcomponents-website/              checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-amaterasu-site/            checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-annotator-website/         checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-ariatosca-website/         checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-brooklyn-site/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-crail-website/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-daffodil-site/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-doris-website/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-druid-website/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-druid-website-src/         checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-dubbo-website/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-echarts-website/           checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-edgent-website/            checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-gobblin-site/              checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-hivemall-site/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-iotdb-website/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-livy-website/              checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-marvin-website/            checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-shardingsphere/            checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-shardingsphere-doc/        checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-superset-site/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-tamaya-site/               checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-toree-website/             checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-tuweni-website/            checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-warble-website/            checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-weex-site/                 checkout     -f  
git  -C   ../mirror/apache-site-git/incubator-zipkin-website/            checkout     -f  
git  -C   ../mirror/apache-site-git/infrastructure-website/              checkout     -f  
git  -C   ../mirror/apache-site-git/isis-site/                           checkout     -f  
git  -C   ../mirror/apache-site-git/james-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/jclouds-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/jmeter-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/jmeter-website/                      checkout     -f  
git  -C   ../mirror/apache-site-git/joshua-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/jspwiki-site/                        checkout     -f  
git  -C   ../mirror/apache-site-git/juneau-website/                      checkout     -f  
git  -C   ../mirror/apache-site-git/kafka-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/karaf-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/kibble-website/                      checkout     -f  
git  -C   ../mirror/apache-site-git/kudu-site/                           checkout     -f  
git  -C   ../mirror/apache-site-git/lucenenet-site/                      checkout     -f  
git  -C   ../mirror/apache-site-git/madlib-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/maven-doxia-site/                    checkout     -f  
git  -C   ../mirror/apache-site-git/maven-doxia-sitetools/               checkout     -f  
git  -C   ../mirror/apache-site-git/maven-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/shiro-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/skywalking-website/                  checkout     -f  
git  -C   ../mirror/apache-site-git/sling-site/                          checkout     -f  
 
git  -C   ../mirror/apache-site-git/struts-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/systemml-website/                    checkout     -f  
git  -C   ../mirror/apache-site-git/tajo-site/                           checkout     -f  
git  -C   ../mirror/apache-site-git/tcl-site/                            checkout     -f  
git  -C   ../mirror/apache-site-git/tomee-site-generator/                checkout     -f  
git  -C   ../mirror/apache-site-git/trafficcontrol-website/              checkout     -f  
git  -C   ../mirror/apache-site-git/trafodion-site/                      checkout     -f  
git  -C   ../mirror/apache-site-git/unomi-site/                          checkout     -f  
git  -C   ../mirror/apache-site-git/whimsy-whimsical-site/               checkout     -f  
git  -C   ../mirror/apache-site-git/wicket-site/                         checkout     -f  
git  -C   ../mirror/apache-site-git/xalan-site/                          checkout     -f  
                                                                         checkout     -f